#!/bin/bash

USERNAME=$2

if [ -z $USERNAME ]; then
  exit 1
fi

case "$1" in

  run) 
    /home/$USERNAME/tinyMediaManager/tinyMediaManagerUpdater.sh
    /home/$USERNAME/tinyMediaManager/tinyMediaManagerCMD.sh -scrapeNew -update
    ;;

  start)
    sleep 1m
    htpcinit-tmm run $USERNAME
    while true
    do
      touch  /tmp/lastwatch-tmm
      sleep 1m
      find /home/$USERNAME/.kodi/userdata/addon_data/plugin.video.netflix/movies /home/$USERNAME/.kodi/userdata/addon_data/plugin.video.netflix/shows -cnewer /tmp/lastwatch-tmm -exec htpcinit-tmm run {} \;
    done
    ;;

esac
