#!/bin/bash

PATH_BASE="$(dirname $0)/../"
source $PATH_BASE/common/paths
source $PATH_BASE/common/functions

function terminate {
  killall -q kodi-standalone
  killall -q kodi
  killall -q kodi.bin
}

function terminate_if_pid_invalid {
  PID=$(get_pid_from_file "$PATH_KODI_PID")
  is_pid_valid_for_name "$PID" "kodi-standalone"
  if [[ ! $? ]]; then
    echo "No valid existing kodi instance found, killing all to ensure PID file cannot be invalid"
    terminate
  fi
}

case "$1" in

  open) 
    terminate_if_pid_invalid
    echo "Opening Kodi"
    kodi-send --action="InhibitIdleShutdown(false)"
    xdotool search --name Kodi windowactivate
    ;;
    
  close) 
    terminate_if_pid_invalid
    echo "Closing Kodi"
    kodi-send --action="PlayerControl(stop)"
    kodi-send --action="InhibitIdleShutdown(true)"
    xdotool search --name Kodi windowminimize
    ;;
    
  restart) 
    terminate_if_pid_invalid
    echo "Restarting Kodi"
    kodi-send --action="RestartApp"
    ;;
    
  backup) 
    echo "Backing up Kodi settings"
    ;;
    
  restore) 
    echo "Restoring and restarting Kodi"
    kodi-send --action="RestartApp"
    ;;
    
  terminate) 
    echo "Terminating Kodi"
    terminate
    ;;

esac