#!/bin/bash

PATH_BASE="$(dirname $0)/../"
source $PATH_BASE/common/paths
source $PATH_BASE/common/functions

function terminate {
  killall -q kodi-standalone
  killall -q kodi
  killall -q kodi.bin
}

function terminate_if_pid_invalid {
  PID=$(get_pid_from_file "$PATH_KODI_PID")
  is_pid_valid_for_name "$PID" "kodi-standalone"
  if [[ ! $? ]]; then
    echo "No valid existing kodi instance found, killing all to ensure PID file cannot be invalid"
    terminate
  fi
}

case "$1" in

  open) 
    terminate_if_pid_invalid
    echo "Opening Kodi"
	  xdotool search --name Kodi windowactivate
	  #wmctrl -lp | awk '$3 == Kodi { print $1 }' | xargs -I {} wmctrl -i -r {} -b remove,hidden,above
    ;;
    
  close) 
    terminate_if_pid_invalid
    echo "Closing Kodi"
	  xdotool search --name Kodi windowminimize
	  #wmctrl -lp | awk '$3 == Kodi { print $1 }' | xargs -I {} wmctrl -i -r {} -b add,hidden
    ;;
    
  terminate) 
    echo "Terminating Kodi"
    terminate
    ;;

esac