#!/bin/bash

PATH_BASE="$(dirname $0)/../"
source $PATH_BASE/common/paths
source $PATH_BASE/common/functions

PID=$(get_pid_from_file "$PATH_STEAM_PID")

case "$1" in

  open_and_wait) 
	$PATH_KODI_CONTROL close
    echo "Opening Steam"
	validate_pid_for_name "$PID" "steam"
	if [ ! $(validate_pid_for_name "$PID" "steam") ]; then
	  echo "No current steam process found, starting anew"
	  steam -bigpicture -steamos &
      PID=$!
      echo "$PID">"$PATH_STEAM_PID"
	else
	  echo "Existing steam process found, resuming"
	  steam steam://open/bigpicture
    fi
	
	while [ $(validate_pid_for_name "$PID" "steam") ]; do
	  sleep 10
	done
	
	$PATH_KODI_CONTROL open
    ;;

  close)
    echo "Closing Steam"
	pkill -f steam
    ;;

esac