#!/bin/bash

# Validate if the given PID matches the given executable name
function is_pid_valid_for_name {
  local PID="$1"
  local NAME="$2"
  if [[ "$NAME" = "$(ps -e | grep $PID | awk '{print $4}')" ]]; then
    return 0
  else
    return 1
  fi
}

# Get the PID from a file
function get_pid_from_file {
  local FILE="$1"
  local PID=0
  if [[ -f "$FILE" ]]; then
    PID=$(<"$FILE")
  fi
  echo "$PID"
}

# See if we can find an active window (an active window should also have a name)
function no_active_window {
  xdotool getactivewindow getwindowname
}